# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fruitCount.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ruitCount.proto\x12\x12grpcProject.protos\"7\n\x06Object\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"?\n\x03Obj\x12*\n\x06\x66ruits\x18\x01 \x03(\x0b\x32\x1a.grpcProject.protos.Object\x12\x0c\n\x04size\x18\x02 \x01(\x05\"2\n\x05\x46ruit\x12)\n\x05\x66ruit\x18\x01 \x01(\x0b\x32\x1a.grpcProject.protos.Object\"6\n\x0b\x46ruitBasket\x12\'\n\x06\x62\x61sket\x18\x01 \x01(\x0b\x32\x17.grpcProject.protos.Obj2X\n\nFruitCount\x12J\n\nFruitCount\x12\x19.grpcProject.protos.Fruit\x1a\x1f.grpcProject.protos.FruitBasket\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fruitCount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECT']._serialized_start=40
  _globals['_OBJECT']._serialized_end=95
  _globals['_OBJ']._serialized_start=97
  _globals['_OBJ']._serialized_end=160
  _globals['_FRUIT']._serialized_start=162
  _globals['_FRUIT']._serialized_end=212
  _globals['_FRUITBASKET']._serialized_start=214
  _globals['_FRUITBASKET']._serialized_end=268
  _globals['_FRUITCOUNT']._serialized_start=270
  _globals['_FRUITCOUNT']._serialized_end=358
# @@protoc_insertion_point(module_scope)
