# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multiSoma.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmultiSoma.proto\x12\x12grpcProject.protos\"\x8c\x01\n\nEntryLongs\x12\x0e\n\x06\x65ntry1\x18\x01 \x01(\x03\x12\x0e\n\x06\x65ntry2\x18\x02 \x01(\x03\x12\x0e\n\x06\x65ntry3\x18\x03 \x01(\x03\x12\x0e\n\x06\x65ntry4\x18\x04 \x01(\x03\x12\x0e\n\x06\x65ntry5\x18\x05 \x01(\x03\x12\x0e\n\x06\x65ntry6\x18\x06 \x01(\x03\x12\x0e\n\x06\x65ntry7\x18\x07 \x01(\x03\x12\x0e\n\x06\x65ntry8\x18\x08 \x01(\x03\"\x13\n\x03Sum\x12\x0c\n\x04soma\x18\x01 \x01(\x03\x32S\n\tMultiSoma\x12\x46\n\tMultiSoma\x12\x1e.grpcProject.protos.EntryLongs\x1a\x17.grpcProject.protos.Sum\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multiSoma_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTRYLONGS']._serialized_start=40
  _globals['_ENTRYLONGS']._serialized_end=180
  _globals['_SUM']._serialized_start=182
  _globals['_SUM']._serialized_end=201
  _globals['_MULTISOMA']._serialized_start=203
  _globals['_MULTISOMA']._serialized_end=286
# @@protoc_insertion_point(module_scope)
