# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxLong.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproxLong.proto\x12\x12grpcProject.protos\"\x1a\n\tEntryLong\x12\r\n\x05\x65ntry\x18\x01 \x01(\x03\"\x18\n\x08NextLong\x12\x0c\n\x04next\x18\x01 \x01(\x03\x32U\n\x08ProxLong\x12I\n\x08ProxLong\x12\x1d.grpcProject.protos.EntryLong\x1a\x1c.grpcProject.protos.NextLong\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxLong_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTRYLONG']._serialized_start=38
  _globals['_ENTRYLONG']._serialized_end=64
  _globals['_NEXTLONG']._serialized_start=66
  _globals['_NEXTLONG']._serialized_end=90
  _globals['_PROXLONG']._serialized_start=92
  _globals['_PROXLONG']._serialized_end=177
# @@protoc_insertion_point(module_scope)
