# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stringComparision.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stringComparision.proto\x12\x12grpcProject.protos\"\x1d\n\x0b\x45ntryString\x12\x0e\n\x06string\x18\x01 \x01(\t\" \n\x0eResponseString\x12\x0e\n\x06string\x18\x01 \x01(\t2o\n\x11StringComparision\x12Z\n\x11StringComparision\x12\x1f.grpcProject.protos.EntryString\x1a\".grpcProject.protos.ResponseString\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stringComparision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTRYSTRING']._serialized_start=47
  _globals['_ENTRYSTRING']._serialized_end=76
  _globals['_RESPONSESTRING']._serialized_start=78
  _globals['_RESPONSESTRING']._serialized_end=110
  _globals['_STRINGCOMPARISION']._serialized_start=112
  _globals['_STRINGCOMPARISION']._serialized_end=223
# @@protoc_insertion_point(module_scope)
